#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2
#SBATCH --mem=32g
#SBATCH --time=02:00:00
#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --account=hpcsuppt_613 
#SBATCH --reservation=bootcamp

module purge
eval "$(conda shell.bash hook)"
conda activate torch_benchmark
python CIFAR10_RestNet50.py