#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2
#SBATCH --mem=32g
#SBATCH --time=02:00:00
#SBATCH --partition=gpu
#SBATCH --gres=gpu:a40:1
#SBATCH --account=wjendrze_120

module purge
eval "$(conda shell.bash hook)"
conda activate torch_benchmark
python CIFAR10_RestNet50.py