#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2
#SBATCH --mem=32g
#SBATCH --time=02:00:00
#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --account=hpcsuppt_613 
#SBATCH --reservation=bootcamp

module purge
singularity exec --bind $PWD --nv pytorch_2.0.1-cuda11.7-cudnn8-runtime.sif python CIFAR10_ResNet50.py
